spring:
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///resumeai?TC_TMPFS=/testtmpfs:rw
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
